version: '3.8'

services:
  # migration:
  #   image: uzman
  #   command: bash -c "python3 ./manage.py makemigrations && python3 ./manage.py migrate && python3 ./manage.py makemigrations inventory && python3 ./manage.py migrate inventory"

  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - pgdb


  pgdb:
    profiles: ['dev']
    container_name: pgdb_ecommerce 
    image: postgres 
    restart: always 
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER= myuser
      - POSTGRES_PASSWORD=mypass

  elasticsearch:
    container_name: search 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

    # image: elasticsearch:7.14.2
    # command: "curl http://localhost:9200"

    # environment: 
    #   - cluster.name= ecommerce-elasticsearch 
    #   - discovery.type= single-node 
    #   - bootstrap.memory_lock=true
    #   - ES_JAVA_OPTS=-Xms128m -Xmx128m
    # ports:
    #   - "9200:9200"
    # volumes:
    #   - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
    # depends_on:
    #   - pgdb 

    


